config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "/", to: redirect("/admins/sign_in")
    post "import_sources/preview", to: "import_sources#preview"
    post "import_sources/:id/sync", to: "import_sources#sync", as: "import_source_sync"
    patch "schools/:id/year", to: "schools#set_current_year", as: "set_current_year"

    resources :import_sources
    resources :schools
    resources :teams do
      resources :players
      resources :events
    end
  end
  devise_for :admins

  as :admin do
    get "admins/edit", to: "devise/registrations#edit", as: :edit_admin_registration
    put "admins", to: "devise/registrations#update", as: :admin_registration
    get "admin/schools", as: :admin_root
  end

  namespace :api do
    namespace :v1 do
      get "teams", to: "teams#teams_by_ids"
      get "live_games", to: "teams#live_games"
      get "recent_results", to: "teams#recent_results"
      get "upcoming_events", to: "teams#upcoming_events"

      resources :devices
      get "schools/:id/upcoming_events", to: "schools#upcoming_events"
      get "schools/:id/recent_results", to: "schools#recent_results"
      get "schools/snap-671/teams.json", to: redirect("/api/v1/schools/snap2-671/teams.json")
      get "schools/snap-678/teams.json", to: redirect("/api/v1/schools/snap2-678/teams.json")
      get "schools/snap-792/teams.json", to: redirect("/api/v1/schools/snap2-792/teams.json")
      get "schools/snap-1182/teams.json", to: redirect("/api/v1/schools/snap2-1182/teams.json")
      resources :schools do
        resources :teams do
          resources :pressbox_posts
          resources :events
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "support/", to: "home#support", as: :support
  get "privacy-policy/", to: "home#privacy_policy", as: :privacy_policy
  get "terms/", to: "home#terms", as: :terms
  root "home#index"
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team

  def to_s
    "#{first_name} #{last_name}"
  end

  def height_humanized
    divmod_output = height.to_i.divmod(12)
    "#{divmod_output[0]}' #{divmod_output[1]}\""
  end
end

app/controllers/admin/players_controller.rb
class Admin::PlayersController < ApplicationController
  before_action :authenticate_admin!
  before_action :require_current_school
  before_action :set_team
  before_action :set_player, only: %i[show edit update destroy]
  layout "admin"

  # GET /players
  def index
    @players = @team.players
  end

  # GET /players/1
  def show
  end

  # GET /players/new
  def new
    @player = @team.players.build
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  def create
    @player = @team.players.build(player_params)
    @player.custom = true

    respond_to do |format|
      if @player.save
        format.turbo_stream
        format.html { redirect_to admin_team_player_url(@team, @player), notice: "Player was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  def update
    @player.assign_attributes(player_params)
    @player.custom = true

    respond_to do |format|
      if @player.save
        format.html do
          redirect_to admin_team_player_url(@team, @player), notice: "Player was successfully updated."
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  def destroy
    @player.destroy

    respond_to do |format|
      format.html { redirect_to admin_players_url, notice: "Player was successfully destroyed." }
      format.turbo_stream
    end
  end

  private

  def set_team
    @team = @current_school.teams.find(params[:team_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_player
    @player = @team.players.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def player_params
    params.require(:player).permit(:first_name, :last_name, :grad_year, :jersey, :position, :height, :weight)
  end
end

app/helpers/admin/players_helper.rb
module Admin::PlayersHelper
end

app/views/admin/players/_form.html.erb
<div class="bg-white rounded shadow px-4 py-6 flex-col text-center items-center h-full aspect-1 max-w-full">
  <%= form_with(model: [:admin, @team, player]) do |form| %>
    <div class="flex justify-center relative mb-4">
      <i class="fas fa-tshirt text-8xl text-primary"></i>
      <div class="absolute w-full h-full text-center items-center justify-center flex">
        <%= form.text_field :jersey, placeholder: '#', class: "shadow rounded-md border-none outline-none px-2 py-1 w-12 text-center font-bold bg-white/50 text-white text-xl font-bold focus:ring-0 placeholder:text-gray-300" %>
      </div>
    </div>

    <div class="flex gap-4 py-px">
      <%= form.text_field :first_name, placeholder: 'First Name', class: "flex-1 shadow rounded-md border border-gray-200 outline-none px-2 py-1 w-full text-right" %>
      <%= form.text_field :last_name, placeholder: 'Last Name', class: "flex-1 shadow rounded-md border border-gray-200 outline-none px-2 py-1 w-full" %>
    </div>

    <div class="mt-4 flex items-center gap-2 text-xs">
      <div class="text-left flex-1">
        <p class="text-gray-500">Position</p>
        <%= form.text_field :position, class: "text-xs font-medium shadow rounded-md border border-gray-200 outline-none px-1 py-1 w-full" %>
      </div>

      <div class="text-left flex-1">
        <p class="text-gray-500">Grad year</p>
        <%= form.text_field :grad_year, class: "text-xs font-medium shadow rounded-md border border-gray-200 outline-none px-1 py-1 w-full" %>
      </div>

      <div class="text-left flex-1">
        <p class="text-gray-500">Height</p>
        <%= form.text_field :height, class: "text-xs font-medium shadow rounded-md border border-gray-200 outline-none px-1 py-1 w-full" %>
      </div>

      <div class="text-left flex-1">
        <p class="text-gray-500">Weight</p>
        <%= form.text_field :weight, class: "text-xs font-medium shadow rounded-md border border-gray-200 outline-none px-1 py-1 w-full" %>
      </div>
    </div>

    <div class="flex mt-4 gap-4">
      <%= link_to "Cancel", admin_team_players_path(@team), class: "rounded-lg py-2 px-2 bg-gray-100 text-black font-medium cursor-pointer flex-1" %>
      <%= form.submit "Save", class: "rounded-lg py-2 px-2 bg-primary text-white font-medium cursor-pointer flex-1" %>
    </div>
  <% end %>
</div>

app/views/admin/players/_new_card.html.erb
<a class="bg-white rounded shadow p-4 h-full aspect-1 max-w-full flex justify-center items-center flex-col gap-4" href="<%= new_admin_team_player_path(@team) %>" data-turbo-frame="<%= dom_id(Player.new) %>">
  <i class="fas fa-plus text-4xl text-primary"></i>
  <p class="text-primary font-bold">Add Player</p>
</a>

app/views/admin/players/_player.html.erb
<%= turbo_frame_tag player do %>
  <div class="bg-white rounded shadow px-4 py-6 flex-col text-center items-center h-full aspect-1 max-w-full">
    <div class="flex justify-center relative mb-4">
      <i class="fas fa-tshirt text-8xl text-primary"></i>
      <span class="absolute w-full h-full text-center items-center justify-center flex text-white text-xl font-bold">
        <%= player.jersey %>
      </span>
    </div>

    <h3 class="text-lg font-bold py-1"><%= player %></h3>

    <div class="mt-4 flex items-center gap-2 text-xs pb-[10px]">
      <div class="text-left flex-1">
        <p class="text-gray-500">Position</p>
        <p class="font-medium"><%= player.position.present? ? player.position : 'N/A' %></p>
      </div>

      <div class="text-left flex-1">
        <p class="text-gray-500">Grad year</p>
        <p class="font-medium"><%= player.grad_year.present? ? player.grad_year : 'N/A' %></p>
      </div>

      <div class="text-left flex-1">
        <p class="text-gray-500">Height</p>
        <p class="font-medium"><%= player.height.present? ? "#{player.height_humanized}" : 'N/A' %></p>
      </div>

      <div class="text-left flex-1">
        <p class="text-gray-500">Weight</p>
        <p class="font-medium"><%= player.weight.present? ? "#{player.weight} lbs" : 'N/A' %></p>
      </div>
    </div>

    <div class="flex mt-4 gap-4">
      <%= button_to 'Delete', admin_team_player_path(@team, player), method: :delete, class: "rounded-lg py-2 px-2 text-black font-medium cursor-pointer flex-1", form: { data: { turbo_confirm: "Are you sure you want to delete this player?" }, class: 'contents' } %>
      <%= link_to "Edit", edit_admin_team_player_path(@team, player), class: "rounded-lg py-2 px-2 bg-primary text-white font-medium cursor-pointer flex-1" %>
    </div>
  </div>
<% end %>

app/views/admin/players/create.turbo_stream.erb
<%= turbo_stream.before Player.new, @player %>
<%= turbo_stream.update Player.new, partial: 'admin/players/new_card' %>

app/views/admin/players/destroy.turbo_stream.erb
<%= turbo_stream.remove @player %>

app/views/admin/players/edit.html.erb
<%= turbo_frame_tag @player do %>
  <%= render "form", player: @player %>
<% end %>

app/views/admin/players/index.html.erb
<% content_for :title, "#{@team} Roster" %>

<%= turbo_frame_tag "players", class: 'grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4' do %>
  <%= render @players %>
  <%= turbo_frame_tag Player.new do %>
    <%= render 'admin/players/new_card' %>
  <% end %>
<% end %>

app/views/admin/players/new.html.erb
<%= turbo_frame_tag @player do %>
  <%= render "form", player: @player %>
<% end %>

app/views/admin/players/show.html.erb
<%= render @player %>