config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "/", to: redirect("/admins/sign_in")
    post "import_sources/preview", to: "import_sources#preview"
    post "import_sources/:id/sync", to: "import_sources#sync", as: "import_source_sync"
    patch "schools/:id/year", to: "schools#set_current_year", as: "set_current_year"

    resources :import_sources
    resources :schools
    resources :teams do
      resources :players
      resources :events
    end
  end
  devise_for :admins

  as :admin do
    get "admins/edit", to: "devise/registrations#edit", as: :edit_admin_registration
    put "admins", to: "devise/registrations#update", as: :admin_registration
    get "admin/schools", as: :admin_root
  end

  namespace :api do
    namespace :v1 do
      get "teams", to: "teams#teams_by_ids"
      get "live_games", to: "teams#live_games"
      get "recent_results", to: "teams#recent_results"
      get "upcoming_events", to: "teams#upcoming_events"

      resources :devices
      get "schools/:id/upcoming_events", to: "schools#upcoming_events"
      get "schools/:id/recent_results", to: "schools#recent_results"
      get "schools/snap-671/teams.json", to: redirect("/api/v1/schools/snap2-671/teams.json")
      get "schools/snap-678/teams.json", to: redirect("/api/v1/schools/snap2-678/teams.json")
      get "schools/snap-792/teams.json", to: redirect("/api/v1/schools/snap2-792/teams.json")
      get "schools/snap-1182/teams.json", to: redirect("/api/v1/schools/snap2-1182/teams.json")
      resources :schools do
        resources :teams do
          resources :pressbox_posts
          resources :events
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "support/", to: "home#support", as: :support
  get "privacy-policy/", to: "home#privacy_policy", as: :privacy_policy
  get "terms/", to: "home#terms", as: :terms
  root "home#index"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :location, optional: true
  has_many :team_events, dependent: :destroy
  has_many :teams, through: :team_events
  has_many :pressbox_posts
  has_many :team_results
  has_one :result
  belongs_to :import_source, optional: true

  scope :upcoming, -> { where(start: Time.now..) }
  scope :past, -> { where(start: ..Time.now) }

  def result_status team
    is_home_team = host_team === team
    if result
      if result.home > result.away
        return is_home_team ? 'win' : 'loss'
      elsif result.away > result.home
        return is_home_team ? 'loss' : 'win'
      else
        return 'tie'
      end
    end
  end

  def opponents team
    teams.select {|t| t.id != team.id}
  end
  
  def self.update_or_create_from_api result
    event = find_by id: "vnn-#{result['id']}"

    if event
      team_events = []

      event = event.tap do |key|
        key.id = "vnn-#{result['id']}"
        key.name = result['name']
        key.event_type = result['event_type']
        key.start = result['start']
        key.tba = result['tba']
        key.result_type = result['result_type']
        key.conference = result['conference']
        key.scrimmage = result['scrimmage']
        key.location_verified = result['location_verified']
        key.canceled = result['canceled']
        key.postponed = result['postponed']
        key.location = Location.find_or_create_from_api result['_embedded']['location'][0] if result['_embedded']['location']
      end

      if event.save
        team_events << TeamEvent.update_or_create_from_api(result, event, Team.find_or_create_from_api(result['_embedded']['team'][0]))

        if result['_embedded']['opponent']
          result['_embedded']['opponent'].each do |opponent|
            url = opponent["_links"]["self"]["href"]

            unless url.include? "opponent"
              fetched_opponent = Vnn::V1::Client.authorized_request(
                http_method: :get, 
                endpoint: url
              )
            end

            if opponent['_embedded'].try(:[], 'team') && !opponent['_embedded']['team'][0].try(:[], 'invalid')
              team_events << TeamEvent.update_or_create_from_api({'_embedded' => result['_embedded']}, event, Team.find_or_create_from_api(fetched_opponent))
            end
          end
        end

        event.team_events.where.not(id: team_events.map(&:id)).destroy_all

        if result['result'].kind_of?(Array)
          event.team_results.destroy_all
          result['result'].each do |result|
            result = result['team']
            TeamResult.create(event: event, team_id: "vnn-#{result['id']}", name: result['name'], place: result['place'], points: result['points'])
          end
        elsif result['result'] && result['result']['away'] && result['result']['home']
          event.result.try(:destroy)
          Result.create(event: event, away: result['result']['away'], home: result['result']['home'])
        end
      end
    else
      event = self.create_from_api result
    end
    
    event
  end

  def self.find_or_create_from_api result
    event = find_by id: "vnn-#{result['id']}"
    event = self.create_from_api result if !event
    
    event
  end
  
  def self.create_from_api result
    event = new do |key|
      key.id = "vnn-#{result['id']}"
      key.name = result['name']
      key.event_type = result['event_type']
      key.start = result['start']
      key.tba = result['tba']
      key.result_type = result['result_type']
      key.conference = result['conference']
      key.scrimmage = result['scrimmage']
      key.location_verified = result['location_verified']
      key.canceled = result['canceled']
      key.postponed = result['postponed']
      key.location = Location.find_or_create_from_api result['_embedded']['location'][0] if result['_embedded']['location']
    end

    if event.save
      TeamEvent.update_or_create_from_api(result, event, Team.find_or_create_from_api(result['_embedded']['team'][0]))

      if result['_embedded']['opponent']
        result['_embedded']['opponent'].each do |opponent|
          url = opponent["_links"]["self"]["href"]

          unless url.include? "opponent"
            fetched_opponent = Vnn::V1::Client.authorized_request(
              http_method: :get, 
              endpoint: url
            )
          end

          if opponent['_embedded'].try(:[], 'team') && !opponent['_embedded']['team'][0].try(:[], 'invalid')
            TeamEvent.update_or_create_from_api({'_embedded' => result['_embedded']}, event, Team.find_or_create_from_api(fetched_opponent))
          end
        end
      end

      if result['result'].kind_of?(Array)
        result['result'].each do |result|
          result = result['team']
          TeamResult.create(event: event, team_id: "vnn-#{result['id']}", name: result['name'], place: result['place'], points: result['points'])
        end
      elsif result['result'] && result['result']['away'] && result['result']['home']
        Result.create(event: event, away: result['result']['away'], home: result['result']['home'])
      end
    end
      
    event
  end

  def host_team
    team_events.select{|team_event| team_event.home}.first.try :team
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  layout "admin"
  before_action :set_event, only: %i[show edit update destroy]
  before_action :set_team

  # GET /events or /events.json
  def index
    @events = @team.events
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @player = @team.events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = @team.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to admin_team_event_url(@team, @event), notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to admin_team_event_url, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to admin_team_events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  def set_team
    @team = Team.find(params[:team_id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :start, :location_id, :location_name)
  end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_school
  before_action :set_team
  before_action :set_event, only: %i[ show ]

  # GET /events
  # GET /events.json
  def index
    @events = @team.events.includes(team_results: [:team]).includes(:result, :teams, :location, :team_events)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = @team.events.find(params[:id])
    end

    def set_team
      @team = @school.teams.find(params[:team_id])
    end

    def set_school
      @school = School.find(params[:school_id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :event_type, :start, :tba, :result_type, :conference, :scrimmage, :location_verified, :private_notes, :public_notes, :bus_dismissal_datetime_local, :bus_departure_datetime_local, :bus_return_datetime_local, :home, :canceled, :postponed, :location_id, :host_team_id)
    end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/api/v1/events_helper.rb
module Api::V1::EventsHelper
end

app/views/admin/events/_event.html.erb
<% team_event = event.team_events.first %>
<% text_style = team_event.try(:team) ? '' : 'line-through text-gray-500' %>

<li class="flex justify-between gap-x-6 py-2 px-4 <%= team_event.try(:team) ? '' : 'bg-gray-100' %>">
  <div class="min-w-0 shrink-0">
    <a href="<%= event.id ? admin_team_event_path(team_id: team_event.try(:team_id) || @team.try(:id), id: event.id) : '' %>" class="text-sm font-semibold leading-6 <%= text_style %>"><%= event.name %></a>
    <p class="text-xs leading-5 text-gray-500 <%= text_style %>"><%= event.start.in_time_zone(@current_school.timezone).strftime('%a, %b %e, %l:%M %p') %></p>
  </div>
  <div class="min-w-0 hidden flex-auto sm:flex sm:flex-col sm:items-end">
    <p class="text-sm leading-6 text-gray-900"><%= team_event.try(:team) || event.result_type %></p>
    <p class="text-xs leading-5 text-gray-500 truncate max-w-full <%= text_style %>">
      <% if team_event && event.location %>
        <b><%= team_event.try(:home) ? 'Home' : 'Away' %></b> - 
      <% end %>
      <%= event.location || event.location_name %>
    </p>
  </div>
</li>

app/views/admin/events/_form.html.erb
<%= form_with(model: [:admin, :team, event], class: "contents") do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :start %>
    <%= form.datetime_field :start, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :location_id %>
        <%= form.collection_select :location_id, @team.events, :id, :name, {prompt: '-- Select Location --'}, {class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full"} %>
  </div>

  <div class="my-5">
    <%= form.label :location_name %>
    <%= form.text_field :location_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/admin/events/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing event</h1>

  <%= render "form", event: @event %>

  <%= link_to "Show this event", @event, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to events", admin_team_events_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/events/index.html.erb
<% content_for :title, "Events" %>
<% content_for :cta, (link_to 'New event', new_admin_team_event_path, class: "rounded-lg py-3 px-5 bg-primary text-white block font-medium") %>

<div class="w-full">
  <div id="events" class="min-w-full">
    <%= render @events %>
  </div>
</div>

app/views/admin/events/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New event</h1>

  <%= render "form", event: @event %>

  <%= link_to 'Back to events', admin_team_events_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/events/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @event %>

    <%= link_to 'Edit this event', edit_admin_team_event_path, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this event', admin_team_event_path, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to events', admin_team_events_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>