config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "/", to: redirect("/admins/sign_in")
    post "import_sources/preview", to: "import_sources#preview"
    post "import_sources/:id/sync", to: "import_sources#sync", as: "import_source_sync"
    patch "schools/:id/year", to: "schools#set_current_year", as: "set_current_year"

    resources :import_sources
    resources :schools
    resources :teams do
      resources :players
      resources :events
    end
  end
  devise_for :admins

  as :admin do
    get "admins/edit", to: "devise/registrations#edit", as: :edit_admin_registration
    put "admins", to: "devise/registrations#update", as: :admin_registration
    get "admin/schools", as: :admin_root
  end

  namespace :api do
    namespace :v1 do
      get "teams", to: "teams#teams_by_ids"
      get "live_games", to: "teams#live_games"
      get "recent_results", to: "teams#recent_results"
      get "upcoming_events", to: "teams#upcoming_events"

      resources :devices
      get "schools/:id/upcoming_events", to: "schools#upcoming_events"
      get "schools/:id/recent_results", to: "schools#recent_results"
      get "schools/snap-671/teams.json", to: redirect("/api/v1/schools/snap2-671/teams.json")
      get "schools/snap-678/teams.json", to: redirect("/api/v1/schools/snap2-678/teams.json")
      get "schools/snap-792/teams.json", to: redirect("/api/v1/schools/snap2-792/teams.json")
      get "schools/snap-1182/teams.json", to: redirect("/api/v1/schools/snap2-1182/teams.json")
      resources :schools do
        resources :teams do
          resources :pressbox_posts
          resources :events
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "support/", to: "home#support", as: :support
  get "privacy-policy/", to: "home#privacy_policy", as: :privacy_policy
  get "terms/", to: "home#terms", as: :terms
  root "home#index"
end

app/models/import_source.rb
class ImportSource < ApplicationRecord
  belongs_to :school
  belongs_to :sport, optional: true
  belongs_to :gender, optional: true
  belongs_to :level, optional: true
  belongs_to :year
  has_many :events, dependent: :destroy
  validates :url, presence: true
  validates :year_id, presence: true
  validates :frequency_hours, presence: true, numericality: { greater_than_or_equal_to: 6, less_than_or_equal_to: 168 }

  def fetch_calendar
    if url.present?
      client = Faraday.new(url: url) do |client|
        client.request :url_encoded
        client.adapter Faraday.default_adapter
      end
      response = client.get.body

      calendar = Icalendar::Calendar.parse(response).first

      calendar_name = calendar.ip_name.try(:first) || ""

      self.name = calendar_name if calendar_name
      return calendar
    end
    Icalendar::Calendar.new
  end

  def possible_teams
    teams = school.teams.includes(:level, :sport, :gender).where(year: year_id)
    teams = teams.where(sport: sport) if sport
    teams = teams.where(gender: gender) if gender
    teams = teams.where(level: level) if level
    teams
  end

  def preview
    teams = possible_teams
    fetch_calendar.events.each do |event|
      add_event event, teams
    end
  end

  def sync
    events.destroy_all
    teams = possible_teams
    fetch_calendar.events.each do |event|
      add_event event, teams, true
    end
    self.last_import_time = DateTime.now
    save
  end

  def add_event(event, teams, sync = false)
    description = event.description || ""
    if level && sport && gender
      team = teams.first
      if team
        add_event_with_team event, team, sync
      else
        handle_missing_event event, sync
      end
    else
      event_length = events.length

      event_results = teams.map do |team|
        cloned_event = event.clone

        matching_sport = if sport
                           true
                         else
                           !!description.match(/\b#{team.sport}\b/) || !!name.match(/\b#{team.sport}\b/)
                         end

        if level
          matching_level = true
        else
          level_abbreviations = team.level.abbreviations
          abbreviation = level_abbreviations.find { |a| description.match(/\b#{a}\b/) }
          if abbreviation
            matching_level = true
            cloned_event.dtstart = cloned_event.dtstart.in_time_zone(school.timezone)
            time = description.match(/\b#{abbreviation}\b - (\d{1,2}:\d{2})\b/).try(:[], 1)
            if time
              hours = time.split(":")[0].to_i
              minutes = time.split(":")[1].to_i
              hours += 12 if cloned_event.dtstart.strftime("%P") == "pm"
              cloned_event.dtstart = cloned_event.dtstart.change({ hour: hours, min: minutes })
            end
          else
            matching_level = !!name.match(/\b#{team.level}\b/)
          end
        end

        matching_gender = if gender
                            true
                          else
                            !!description.match(/\b#{team.gender}\b/) || !!name.match(/\b#{team.gender}\b/)
                          end

        add_event_with_team cloned_event, team, sync if matching_sport && matching_level && matching_gender
        { matching_sport: matching_sport, matching_level: matching_level, matching_gender: matching_gender }
      end

      handle_missing_event event, sync, event_results if events.length == event_length && !sync
    end
  end

  def add_event_with_team(event, team, sync)
    if sync && event.location
      short = event.location.length < 5

      if short && school.location
        location_results = if event.location.present?
                             Geocoder.search("#{event.location} #{school.location.city}",
                                             locationbias: "point:#{school.location.latitude},#{school.location.longitude}")
                           else
                             []
                           end
      else
        location_results = event.location.present? ? Geocoder.search(name: event.location) : []
      end
      location_result = location_results.first

      timezone = Timezone["America/New_York"]

      if location_result && location_result.place_id
        location_place = Geocoder.search(location_result.place_id, lookup: :google_places_details).first
        if location_place && location_place.street_address.present?
          timezone = Timezone.lookup(location_place.latitude, location_place.longitude)
          new_location_record = Location.new(
            name: location_place.data["name"],
            address_1: location_place.street_address,
            city: location_place.city,
            state: location_place.state,
            zip: location_place.postal_code,
            latitude: location_place.latitude,
            longitude: location_place.longitude,
            timezone: timezone.name
          )
          home = school.location.distance_to(new_location_record) < 2
          unless new_location_record.name
            new_location_record.name = home ? school.location.name : event.summary
          end
        end
      end
    end

    events.build(
      start: event.dtstart,
      name: event.summary,
      location_name: event.location,
      location: event.location ? new_location_record : school.location,
      team_events: [
        team.team_events.build(opponent_name: event.summary, home: home)
      ]
    )
  end

  def handle_missing_event(event, sync, event_results = [])
    missing = []
    if event_results.length > 0
      missing << "sport" if event_results.all? { |result| !result[:matching_sport] }
      missing << "level" if event_results.all? { |result| !result[:matching_level] }
      missing << "gender" if event_results.all? { |result| !result[:matching_gender] }
      message =  "Unable to detect #{missing.to_sentence} from: \"#{event.description}\""
    else
      missing << "Sport: #{sport}" if sport
      missing << "Level: #{level}" if level
      missing << "Gender: #{gender}" if gender
      message =  "You don't have a team setup with #{missing.to_sentence}"
    end

    return if sync

    events.build(
      start: event.dtstart,
      name: event.summary,
      location_name: event.location,
      result_type: message
    )
  end
end

app/models/year.rb
class Year < ApplicationRecord
  has_many :teams

  def self.current
    Year.all.find {|year| DateTime.now.between? year.start, year.end}
  end

  def self.find_or_create_from_api result
    year = find_by id: result['id']
    if !year
      year = new do |key|
        key.id = result['id']
        key.name = result['name']
        key.start = result['start']
        key.end = result['end']
      end

      year.save
    end
    
    year
  end

  def to_s
    name
  end
end

app/controllers/admin/import_sources_controller.rb
class Admin::ImportSourcesController < ApplicationController
  before_action :authenticate_admin!
  before_action :require_current_school
  before_action :set_import_source, only: %i[show edit update destroy sync]
  layout "admin"

  # GET /import_sources
  def index
    @import_sources = @current_school.import_sources.where(year: selected_year_id)
  end

  # GET /import_sources/1
  def show
    @events = @import_source.events.includes(:location, :team_events)
  end

  # GET /import_sources/new
  def new
    @import_source = @current_school.import_sources.new
  end

  # GET /import_sources/1/edit
  def edit
    @import_source.preview
  end

  # POST /import_sources
  def create
    @import_source = @current_school.import_sources.new(import_source_params)
    @import_source.year_id = selected_year_id

    respond_to do |format|
      if @import_source.save
        ImportSourceJob.perform_later @import_source
        format.html do
          redirect_to admin_import_source_url(@import_source), notice: "Import source was successfully created."
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /import_sources/1
  def update
    respond_to do |format|
      if @import_source.update(import_source_params)
        ImportSourceJob.perform_later @import_source
        format.html do
          redirect_to admin_import_source_url(@import_source), notice: "Import source was successfully updated."
        end
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /import_sources/1
  def destroy
    @import_source.destroy

    respond_to do |format|
      format.html { redirect_to admin_import_sources_url, notice: "Import source was successfully destroyed." }
    end
  end

  # POST /import_sources/1/sync
  def sync
    ImportSourceJob.perform_later @import_source

    respond_to do |format|
      format.html { redirect_to admin_import_source_url(@import_source), notice: "Sync started." }
    end
  end

  # DELETE /import_sources/1 or /import_sources/1.json
  def preview
    @import_source = @current_school.import_sources.find_by(id: params[:id])
    @import_source ||= @current_school.import_sources.new
    @import_source.assign_attributes(import_source_params)
    @import_source.year_id = selected_year_id
    @import_source.preview

    respond_to do |format|
      if @import_source.persisted?
        format.html { render :edit, status: @import_source.valid? ? :found : :unprocessable_entity }
      else
        format.html { render :new, status: @import_source.valid? ? :found : :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_import_source
    @import_source = @current_school.import_sources.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def import_source_params
    params.require(:import_source).permit(:name, :url, :sport_id, :gender_id, :level_id, :frequency_hours)
  end
end

app/helpers/admin/import_sources_helper.rb
module Admin::ImportSourcesHelper
end

app/views/admin/import_sources/_form.html.erb
<div data-controller="forms" class="contents">
  <%= form_with(model: [:admin, import_source], url: import_source.events.length > 0 ? nil : admin_import_sources_preview_path, class: "contents", method: import_source.events.length > 0 ? nil : :post, data: {forms_target: "form"}) do |form| %>
    <% if import_source %>
      <%= hidden_field_tag :id, import_source.id %>
    <% end %>
    
    <% if import_source.errors.any? %>
      <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
        <h2><%= pluralize(import_source.errors.count, "error") %> prohibited this import_source from being saved:</h2>

        <ul>
          <% import_source.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="my-5">
      <%= form.label :url %>
      <%= form.text_field :url, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full #{import_source.url.present? ? 'bg-gray-100' : ''}", readonly: import_source.url.present? %>
    </div>

    <% if import_source.url.present? %>
      <div class="my-5 flex gap-5 flex-col md:flex-row">
        <div class="flex-1">
          <%= form.label :sport_id %>
          <%= form.collection_select :sport_id, Sport.includes(:teams).where(teams: {id: @current_school.team_ids}).order(:name), :id, :name, {include_blank: '-- Automatically Detect --'}, {class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: { action: "change->forms#submit" }} %>
        </div>

        <div class="flex-1">
          <%= form.label :level_id %>
          <%= form.collection_select :level_id, Level.includes(:teams).where(teams: {id: @current_school.team_ids}), :id, :name, {include_blank: '-- Automatically Detect --'}, {class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: { action: "change->forms#submit" }} %>
        </div>

        <div class="flex-1">
          <%= form.label :gender_id %>
          <%= form.collection_select :gender_id, Gender.includes(:teams).where(teams: {id: @current_school.team_ids}), :id, :name, {include_blank: '-- Automatically Detect --'}, {class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", data: { action: "change->forms#submit" }} %>
        </div>
      </div>

      <div class="my-5">
        <%= form.label :name %>
        <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.label :frequency_hours, "Import frequency (hours)" %>
        <%= form.number_field :frequency_hours, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <% events = import_source.events.select{ |event| !event.persisted? } %>
      <% if events.length > 0 %>
        <div class="rounded-md shadow bg-white mb-4">
          <h2 class="text-lg px-4 py-2 font-bold border-b border-gray-100">Events Preview</h2>
          <ul role="list" class="divide-y divide-gray-100">
            <% events.each do |event| %>
              <%= render "admin/events/event", event: event %>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="inline">
        <%= form.submit "Import", class: "rounded-lg py-3 px-5 bg-primary text-white inline-block font-medium cursor-pointer" %>
      </div>
    <% else %>
      <div class="inline">
        <%= form.submit "Preview", class: "rounded-lg py-3 px-5 bg-primary text-white inline-block font-medium cursor-pointer" %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/admin/import_sources/_import_source.html.erb
<<%= action_name == "show" ? 'div' : 'a' %> id="<%= dom_id import_source %>" class="bg-white rounded shadow p-6 flex flex-col gap-4" href="<%= url_for [:admin, import_source] %>">
  <h2 class="text-lg font-bold"><%= import_source.name %></h2>

  <p>Imports events <b>every <%= pluralize(import_source.frequency_hours, 'Hour') %></b> from <b><%= URI(import_source.url).host %></b></p>

  <div class="flex items-center gap-2 text-xs">
    <div class="text-left flex-1">
      <p class="text-gray-500">Sport</p>
      <p class="font-medium"><%= import_source.sport ? import_source.sport : 'Auto' %></p>
    </div>

    <div class="text-left flex-1">
      <p class="text-gray-500">Level</p>
      <p class="font-medium"><%= import_source.level ? import_source.level : 'Auto' %></p>
    </div>

    <div class="text-left flex-1">
      <p class="text-gray-500">Gender</p>
      <p class="font-medium"><%= import_source.gender ? import_source.gender : 'Auto' %></p>
    </div>
  </div>

  <p class="text-xs text-gray-500">
    <%= import_source.last_import_time ? "Last Imported on #{import_source.last_import_time.in_time_zone(@current_school.timezone).strftime('%D at %l:%M %p %Z')}" : 'Import Running Now' %>
  </p>
</<%= action_name == "show" ? 'div' : 'a' %>>

app/views/admin/import_sources/edit.html.erb
<% content_for :title, "\"#{@import_source.name}\" Settings" %>

<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", import_source: @import_source %>

  <%= link_to "Back", :back, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/import_sources/index.html.erb
<% content_for :title, "Import Sources" %>
<% content_for :cta, (link_to 'New import', new_admin_import_source_path, class: "rounded-lg py-3 px-5 bg-primary text-white block font-medium") %>

<div class="w-full">
  <div id="import_sources" class="grid grid-cols-1 lg:grid-cols-2 gap-4">
    <%= render @import_sources %>
  </div>
</div>

app/views/admin/import_sources/new.html.erb
<% content_for :title, "New Import Source" %>

<div class="mx-auto md:w-2/3 w-full">
  <%= render "form", import_source: @import_source %>

  <%= link_to "Back", :back, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/admin/import_sources/show.html.erb
<% content_for :title, "\"#{@import_source.name}\" Details" %>
<% content_for :cta_secondary, (button_to 'Sync Now', admin_import_source_sync_path(@import_source), class: "rounded-lg py-3 px-5 block font-medium", method: :post) %>
<% content_for :cta, (link_to 'Settings', edit_admin_import_source_path(@import_source), class: "rounded-lg py-3 px-5 bg-primary text-white block font-medium") %>

<div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
  <div>
    <%= render @import_source %>
  </div>
  
  <div>
    <div class="bg-white rounded shadow p-2">
      <h2 class="text-lg font-bold p-4">
        Events
      </h2>

      <% if @events.length > 0 %>
        <ul role="list" class="divide-y divide-gray-100">
          <% @events.each do |event| %>
            <%= render "admin/events/event", event: event %>
          <% end %>
        </ul>
      <% else %>
        <p class="text-sm px-4 pb-4">No imported events.</p>
      <% end %>
    </div>
  </div>
</div>