config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get "/", to: redirect("/admins/sign_in")
    post "import_sources/preview", to: "import_sources#preview"
    post "import_sources/:id/sync", to: "import_sources#sync", as: "import_source_sync"
    patch "schools/:id/year", to: "schools#set_current_year", as: "set_current_year"

    resources :import_sources
    resources :schools
    resources :teams do
      resources :players
      resources :events
    end
  end
  devise_for :admins

  as :admin do
    get "admins/edit", to: "devise/registrations#edit", as: :edit_admin_registration
    put "admins", to: "devise/registrations#update", as: :admin_registration
    get "admin/schools", as: :admin_root
  end

  namespace :api do
    namespace :v1 do
      get "teams", to: "teams#teams_by_ids"
      get "live_games", to: "teams#live_games"
      get "recent_results", to: "teams#recent_results"
      get "upcoming_events", to: "teams#upcoming_events"

      resources :devices
      get "schools/:id/upcoming_events", to: "schools#upcoming_events"
      get "schools/:id/recent_results", to: "schools#recent_results"
      get "schools/snap-671/teams.json", to: redirect("/api/v1/schools/snap2-671/teams.json")
      get "schools/snap-678/teams.json", to: redirect("/api/v1/schools/snap2-678/teams.json")
      get "schools/snap-792/teams.json", to: redirect("/api/v1/schools/snap2-792/teams.json")
      get "schools/snap-1182/teams.json", to: redirect("/api/v1/schools/snap2-1182/teams.json")
      resources :schools do
        resources :teams do
          resources :pressbox_posts
          resources :events
        end
      end
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  get "support/", to: "home#support", as: :support
  get "privacy-policy/", to: "home#privacy_policy", as: :privacy_policy
  get "terms/", to: "home#terms", as: :terms
  root "home#index"
end

app/views/layouts/admin.html.erb
<% nav_items = @current_school.persisted? ? [['Dashboard', admin_school_path(@current_school)], ['Teams', admin_teams_path], ['Imports', admin_import_sources_path]] : [] %>
<% profile_nav_items = [['Your Profile', edit_admin_registration_path], ['Sign out', destroy_admin_session_path, 'delete']] %>
<% schools = current_admin ? current_admin.schools.where.not(id: @current_school) : [] %>
<% if @team && @team.persisted? %>
  <% nav_items << ['Events', admin_team_events_path(@team)] %>
  <% nav_items << ['Roster', admin_team_players_path(@team)] %>
<% end %>
<!DOCTYPE html>
<html>
  <head>
    <title>My Schools Sports</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "fonts", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="h-full bg-gray-100">
    <style>
      :root {
        --primary-color: <%= @current_school.primary_color || "#000" %>;
      }
    </style>
    <div class="min-h-full">
      <nav class="bg-primary" data-controller="toggle">
        <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div class="flex h-16 items-center justify-between">
            <div class="flex items-center">
              <div class="flex-shrink-0 relative" data-controller="toggle">
                <a class="<%= @current_school.persisted? ? 'bg-white' : 'bg-black' %> p-2 rounded block" href="<%= @current_school.persisted? ? admin_school_path(@current_school) : admin_schools_path %>" data-action="mouseover->toggle#show mouseout->toggle#hide">
                  <img class="h-8 w-8" src="<%= @current_school.logo_url %>" alt="<%= @current_school.name %>">
                </a>

                <% if schools.length > 0 %>
                  <div class="absolute right-0 z-10 origin-top-right py-2 gap-1 hidden flex flex-col" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1" data-toggle-target="toggleable" data-action="mouseover->toggle#show mouseout->toggle#hide">
                    <% schools.each do |school| %>
                      <a class="block p-2 rounded bg-white hover:bg-gray-200 shadow" href="<%= admin_school_path(school) %>">
                        <img class="h-8 w-8" src="<%= school.logo_url %>" alt="<%= school.name %>">
                      </a>
                    <% end %>
                  </div>
                <% end %>
              </div>
              <div class="hidden md:block">
                <div class="ml-10 flex items-baseline space-x-4">
                  <% nav_items.each do |title, url| %>
                    <% if current_page? url %>
                      <a href="<%= url %>" class="bg-white text-primary rounded-md px-3 py-2 text-sm font-medium" aria-current="page"><%= title %></a>
                    <% else %>
                      <a href="<%= url %>" class="text-white hover:bg-gray-200 hover:text-primary rounded-md px-3 py-2 text-sm font-medium"><%= title %></a>
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="hidden md:block flex-1">
              <div class="ml-4 flex items-center md:ml-6 justify-end">
                <% if admin_signed_in? %>
                  <% if @current_school.persisted? %>
                    <%= form_with url: admin_set_current_year_path(@current_school.id), method: :patch do |form| %>
                      <%= collection_select nil, :year_id, Year.order(:name).reverse, :id, :name, {selected: selected_year_id}, {class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 w-36", id: 'current_year_select'} %>
                    <% end %>
                  <% end %>

                  <div class="relative ml-3" data-controller="toggle">
                    <button type="button" class="relative flex max-w-xs items-center rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true" data-action="click->toggle#toggle touch->toggle#toggle">
                      <span class="absolute -inset-1.5"></span>
                      <span class="sr-only">Open user menu</span>
                      <img class="h-8 w-8 rounded-full" src="https://t3.ftcdn.net/jpg/05/16/27/58/360_F_516275801_f3Fsp17x6HQK0xQgDQEELoTuERO4SsWV.jpg" alt="">
                    </button>

                    <div class="absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none hidden" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1" data-toggle-target="toggleable">
                      <% profile_nav_items.each do |title, url, method| %>
                        <% if current_page? url %>
                          <a href="<%= url %>" class="block px-4 py-2 text-sm text-gray-700 bg-gray-100" role="menuitem" tabindex="-1" data-turbo-method="<%= method %>"><%= title %></a>
                        <% else %>
                          <a href="<%= url %>" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" data-turbo-method="<%= method %>"><%= title %></a>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                <% else %>
                  <a href="<%= new_admin_session_path %>" class="text-white hover:bg-gray-200 hover:text-primary rounded-md px-3 py-2 text-base font-medium block" aria-current="page">Login</a>
                <% end %>
              </div>
            </div>
            <div class="-mr-2 flex md:hidden">
              <!-- Mobile menu button -->
              <button type="button" class="relative inline-flex items-center justify-center rounded-md bg-gray-800 p-2 text-white hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" aria-controls="mobile-menu" aria-expanded="false" data-action="click->toggle#toggle touch->toggle#toggle">
                <span class="absolute -inset-0.5"></span>
                <span class="sr-only">Open main menu</span>
                <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-toggle-target="toggleable">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
                </svg>
                <svg class="hidden h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-toggle-target="toggleable">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
          </div>
        </div>

        <!-- Mobile menu, show/hide based on menu state. -->
        <div class="hidden md:hidden" id="mobile-menu" data-toggle-target="toggleable">
          <div class="space-y-1 px-2 pb-3 pt-2 sm:px-3">
            <% nav_items.each do |title, url| %>
              <% if current_page? url %>
                <a href="<%= url %>" class="bg-white text-primary rounded-md px-3 py-2 text-base font-medium block" aria-current="page"><%= title %></a>
              <% else %>
                <a href="<%= url %>" class="text-white hover:bg-gray-200 hover:text-primary rounded-md px-3 py-2 text-base font-medium  block"><%= title %></a>
              <% end %>
            <% end %>
          </div>
          <div class="border-t border-gray-700 pb-3 pt-4">
            <% if admin_signed_in? %>
              <div class="flex items-center px-5">
                <div class="flex-shrink-0">
                  <img class="h-10 w-10 rounded-full" src="https://t3.ftcdn.net/jpg/05/16/27/58/360_F_516275801_f3Fsp17x6HQK0xQgDQEELoTuERO4SsWV.jpg" alt="">
                </div>
                <div class="ml-3 flex flex-col gap-1">
                  <div class="text-base font-medium leading-none text-white"><%= current_admin.name %></div>
                  <div class="text-sm font-medium leading-none text-gray-100"><%= current_admin.email %></div>
                </div>
              </div>
              <div class="mt-3 space-y-1 px-2">
                <% profile_nav_items.each do |title, url, method| %>
                  <% if current_page? url %>
                    <a href="<%= url %>" class="bg-white text-primary rounded-md px-3 py-2 text-base font-medium block" aria-current="page" data-turbo-method="<%= method %>"><%= title %></a>
                  <% else %>
                    <a href="<%= url %>" class="text-white hover:bg-gray-200 hover:text-primary rounded-md px-3 py-2 text-base font-medium block" data-turbo-method="<%= method %>"><%= title %></a>
                  <% end %>
                <% end %>
              </div>
            <% else %>
              <a href="<%= new_admin_session_path %>" class="text-white hover:bg-gray-200 hover:text-primary rounded-md px-3 py-2 text-base font-medium block" aria-current="page">Login</a>
            <% end %>
          </div>
        </div>
      </nav>

      <header class="bg-white shadow">
        <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8 flex justify-between items-center">
          <h1 class="text-3xl font-bold tracking-tight text-gray-900 py-2"><%= yield(:title) %></h1>
          <div class="flex gap-2">
            <%= yield(:cta_secondary) %>
            <%= yield(:cta) %>
          </div>
        </div>
      </header>
      <main>
        <div class="mx-auto max-w-7xl py-6 px-4 sm:px-6 lg:px-8">
          <% if notice.present? %>
            <p class="py-3 px-4 bg-green-50 mb-5 text-green-700 font-medium rounded-lg block shadow" id="notice"><%= notice %></p>
          <% end %>
          <% if alert.present? %>
            <p class="py-3 px-4 bg-yellow-50 mb-5 text-yellow-700 font-medium rounded-lg block shadow" id="alert"><%= alert %></p>
          <% end %>
          <%= yield %>
        </div>
      </main>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Schools Sports</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main id="main">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </main>
  </body>
</html>